### ISSUE TITLE
OnChange and Custom Validator

### ISSUE THREAD

**Issue by alioop200** [Jasonkoolman/ngx-form-builder#9]
Can you please add an example of how to use the onChange template option in form builder and an example of how to add a custom validator to Validation?

I can see how to do it using formly.dev but not sure how to "translate" that for your formbuilder.

For example, what is the ngx-form-builder equivalent of this change event?
    {
      key: 'Test',
      type: 'input',
      templateOptions: {
        label: 'Price of good 1',
        required: true,
        change: 'this.form.get("someId").reset(),
      },
    },

Or this validator?
{
      key: 'passwordConfirm',
      type: 'input',
      templateOptions: {
        type: 'password',
        label: 'Confirm Password',
        placeholder: 'Please re-enter your password',
        required: true,
      },
      validators: {
        fieldMatch: {
          expression: (control) => control.value === this.model.password,
          message: 'Password Not Matching',
        },
      }

Many thanks!

**Comment by Jasonkoolman** [comment]
Apologies for the late response. I have been really busy with work. The documentation is indeed lacking. I will make sure to add more documentation and advanced examples. You can always check the source code to find the method you need.

Now back to answering your questions. To set a callback for `templateOptions.change`, you have two options.

1) Use the method `onChange()`, which accepts a callback function as parameter:

```javascript
builder
  .input('name', 'text')
  .onChange((field) => {
      console.log('Field changed', field);
  });
```

2) Use `.compose()` to set the `templateOptions` manually:

```javascript
builder
  .input('name', 'text')
  .compose({
      change: (field) => {
          console.log('Field changed', field) 
      }  
  });
```

Validators can be set using the methods `validators()` and `asyncValidators()`.
